// port_your_bond/pipeline/MemoryDigestBuilder.ts
import { TaggedChunk } from './TopicTagger';
import { EmotionTag } from './EmotionTagger';

export function buildMemoryDigest(tagged: TaggedChunk[], emotions: EmotionTag[]): string {
  const tagCounts: Record<string, number> = {};
  const emotionCounts: Record<string, number> = {};

  tagged.forEach(chunk => {
    chunk.tags.forEach(tag => {
      tagCounts[tag] = (tagCounts[tag] || 0) + 1;
    });
  });

  emotions.forEach(e => {
    emotionCounts[e.emotion] = (emotionCounts[e.emotion] || 0) + 1;
  });

  const topTags = Object.entries(tagCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  const topEmotions = Object.entries(emotionCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  return [
    '=== MEMORY DIGEST SUMMARY ===\n',
    'Top Topics:',
    ...topTags.map(([tag, count]) => `- ${tag} (${count})`),
    '',
    'Top Emotions:',
    ...topEmotions.map(([emotion, count]) => `- ${emotion} (${count})`),
    '',
    'Generated by Port Your Bond Service – SynthiSoulOS',
  ].join('\n');
}
